# Generated by Django 4.0.3 on 2023-07-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_newuser_docname_document_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='interests',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('music', 'Music'), ('books', 'Books')], max_length=255, null=True),
        ),
    ]
