# Generated by Django 4.0.3 on 2023-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_newuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
